<template>

<section class="message-wrap">
    <div class="container">
        <div class="row">
            <h2 class="col-lg-9 col-md-8 col-sm-12 col-xs-12">Discover a website for car dealers that converts visitors to <span class="alternate-font">customers</span></h2>
            <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12"> <a href="#" class="default-btn pull-right action_button lg-button">Schedule a Test Drive</a> </div>
        </div>
    </div>
    <div class="message-shadow"></div>
</section>
</template>
<script>
export default {
    name:'MessagePart',
}
</script>